### ISSUE TITLE
Can you make this plugin and the free sticker plugin work with this line?

### ISSUE THREAD

**Issue by ZellsAlpha** [An00nymushun/DiscordFreeEmojis#42]
Adding this so the actual icons themselves become colored, breaks this script and the free stickers script.

BdApi.findModuleByProps("getCurrentUser").getCurrentUser().premiumType = 2;

This line pretty much makes it show the icons in the emoji menu in color, but script doesn't seem to work with it on, same thing with stickers, they don't send

**Comment by An00nymushun** [comment]
Use css to make them non grayscale.
That line spoofs nitro, which breaks functionalities because you don't actually have nitro and the backend rejects your requests.

**Comment by ZellsAlpha** [comment]
no clue how to do that 🤷

**Comment by marcussacana** [comment]
```css
li[class*='emojiItemDisabled'] { 
    outline: dotted 1px rgba(255, 0, 0, 0.3); 
    outline-offset: -2px; 
    filter: none !important; 
    cursor: pointer; 
}

li[class*='emojiItemDisabled'] > img { 
     filter: none; 
}
```

**Comment by neemanthnub** [comment]
> ```css
> li[class*='emojiItemDisabled'] { 
>     outline: dotted 1px rgba(255, 0, 0, 0.3); 
>     outline-offset: -2px; 
>     filter: none !important; 
>     cursor: pointer; 
> }
> 
> li[class*='emojiItemDisabled'] > img { 
>      filter: none; 
> }
> ```

Hi, do we just have to paste this in the custom CSS editor?

**Comment by marcussacana** [comment]
Yes, but is outdated, this one should works:
```css
button[class*='emojiItemDisabled']{ 
    outline: dotted 1px rgba(255, 0, 0, 0.3); 
    outline-offset: -2px; 
    filter: none !important; 
    cursor: pointer; 
}

button[class*='emojiItemDisabled'] > * { 
     filter: none !important; 
}
```

**Comment by neemanthnub** [comment]
> Yes, but is outdated, this one should works:
> 
> ```css
> button[class*='emojiItemDisabled']{ 
>     outline: dotted 1px rgba(255, 0, 0, 0.3); 
>     outline-offset: -2px; 
>     filter: none !important; 
>     cursor: pointer; 
> }
> 
> button[class*='emojiItemDisabled'] > * { 
>      filter: none !important; 
> }
> ```

thank you, its working

**Comment by FrostBird347** [comment]
If you still want to be able to quickly differentiate between emojis that will be embedded and ones that are in your current server, you can use this instead:
```css
button[class*='emojiItemSelected'] {
    filter: none !important
}
```
With this, only selected emotes will not be greyscale.
