### ISSUE TITLE
Remove gray filter in emoji picker

### ISSUE THREAD

**Issue by DiamondMiner88** [An00nymushun/DiscordFreeEmojis#8]
If you do not have nitro all the emojis from other servers are grayed out in the emoji picker.
Not sure where to edit the plugin to submit a pr so I'll post here.
```css
.emojiItemDisabled-1FvFuF {
    -webkit-filter: grayscale(0%);
    filter: grayscale(0%);
}
```
Adding this to custom css removes the gray filter.

**Comment by An00nymushun** [comment]
It's intentionally left like that (and it wasn't easy figuring it out), so you can know which emojis are sent normally.

**Comment by DiamondMiner88** [comment]
Can a setting be added to disable the grayscale?

**Comment by da19961** [comment]
> It's intentionally left like that (and it wasn't easy figuring it out), so you can know which emojis are sent normally.

How about removing the gray filter when hovering over the emoji?

**Comment by An00nymushun** [comment]
> How about removing the gray filter when hovering over the emoji?

You can see the colored versions at the bottom of the emoji picker when hovering over them.

**Comment by KraXen72** [comment]
you can use custom css to ungrayscale them.

**Comment by marcussacana** [comment]
I'm did this CSS because will remove the grayscale and I still know what is locked emoji
```css
li[class*='emojiItemDisabled'] { 
  filter: none !important; 
  outline: dotted 1px rgba(255, 0, 0, 0.3); 
  outline-offset: -2px; 
}
```
![image](https://user-images.githubusercontent.com/10576957/115133932-3bd25f00-9fe2-11eb-9d09-b3feeb01e802.png)

**Comment by Nexuzzzz** [comment]
> I'm did this CSS because will remove the grayscale and I still know what is locked emoji
> 
> ```css
> li[class*='emojiItemDisabled'] { 
>   filter: none !important; 
>   outline: dotted 1px rgba(255, 0, 0, 0.3); 
>   outline-offset: -2px; 
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/10576957/115133932-3bd25f00-9fe2-11eb-9d09-b3feeb01e802.png)

cheers xd

**Comment by CharlesAttend** [comment]
Replacing `li` with `button` work for me 
```css
button[class*='emojiItemDisabled'] { 
  filter: none !important; 
  outline: dotted 1px rgba(255, 0, 0, 0.3); 
  outline-offset: -2px; 
}
```
